// FILE: /pages/legal.js
import Head from "next/head";
import Link from "next/link";
import Footer from "../components/Footer";

export default function LegalPage() {
  return (
    <div className="page">
      <Head>
        <title>Legal Disclaimer & Liability | Total-Iora Voice</title>
        <meta
          name="description"
          content="Legal Disclaimer, Limitation of Liability, and Terms for Total-Iora Voice and Leffler International Investments."
        />
      </Head>

      <nav className="topnav">
        <Link href="/" className="logoLink">
          ← Back to Home
        </Link>
      </nav>

      <main className="mainContent">
        <div className="legalCard">
          <h1>Legal Disclaimer & Limitation of Liability</h1>
          <p className="lastUpdated">
            <strong>Last updated: December 21, 2025</strong>
          </p>

          <p>
            Please read this document carefully. By accessing or using the Total-Iora website, 
            applications, or services (collectively, the "Service"), you agree to be bound by 
            the following disclaimers and limitations of liability.
          </p>

          <h2>1. Entertainment & Spiritual Reflection Only</h2>
          <p>
            The Service, including "Oracle Universe DNA" and "Sacred Notes," is provided strictly 
            for <strong>entertainment, spiritual reflection, and contemplation purposes only</strong>. 
            The content generated by the Service is symbolic and metaphorical.
          </p>
          <p>
            <strong>We are NOT offering treatments, medical advice, psychological counseling, 
            financial advice, or legal counsel.</strong>
          </p>

          <h2>2. No Professional Advice</h2>
          <ul>
            <li>
              <strong>Medical:</strong> Nothing on this site should be considered medical advice or 
              a substitute for professional healthcare. Do not ignore professional medical advice 
              because of something you have read or heard on this Service.
            </li>
            <li>
              <strong>Financial/Legal:</strong> We do not provide financial investment recommendations 
              or legal opinions. You are responsible for your own financial and legal decisions.
            </li>
          </ul>

          <h2>3. Liability Protection for Leffler International Investments</h2>
          <p>
            To the fullest extent permitted by applicable law, <strong>Leffler International Investments</strong>, 
            its owners, subsidiaries, affiliates, officers, directors, employees, agents, partners, 
            and licensors (collectively, the "Protected Parties") shall NOT be liable for any:
          </p>
          <ul>
            <li>Direct, indirect, incidental, special, consequential, or punitive damages.</li>
            <li>Loss of profits, data, use, goodwill, or other intangible losses.</li>
            <li>Personal injury or emotional distress resulting from your use of the Service.</li>
          </ul>
          <p>
            You expressly acknowledge that the Protected Parties are not responsible for any interpretation 
            or action you take based on the symbolic guidance provided by the Service.
          </p>

          <h2>4. Assumption of Risk</h2>
          <p>
            You agree that your use of the Service is at your sole risk. The Service is provided 
            on an "AS IS" and "AS AVAILABLE" basis. The Protected Parties expressly disclaim all 
            warranties of any kind, whether express or implied.
          </p>

          <h2>5. Indemnification</h2>
          <p>
            You agree to defend, indemnify, and hold harmless <strong>Leffler International Investments</strong>,
            and its employees/contractors from and against any claims, liabilities, damages, judgments,
            awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of
            or relating to your violation of these Terms or your use of the Service.
          </p>

          <div className="copyrightBox">
            <p>&copy; {new Date().getFullYear()} Leffler International Investments. All rights reserved.</p>
          </div>
        </div>
      </main>

      <Footer />

      <style jsx>{`
        .page {
          min-height: 100vh;
          background: linear-gradient(#ffffff, #f8fafc);
          color: #334155;
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        }

        .topnav {
          padding: 20px;
          text-align: center;
        }

        .logoLink {
          text-decoration: none;
          color: #64748b;
          font-weight: 700;
          font-size: 0.95rem;
        }
        .logoLink:hover {
          color: #0f172a;
          text-decoration: underline;
        }

        .mainContent {
          padding: 20px 16px 60px;
        }

        .legalCard {
          max-width: 800px;
          margin: 0 auto;
          background: #fff;
          border: 1px solid #e2e8f0;
          border-radius: 24px;
          padding: 40px;
          box-shadow: 0 10px 40px rgba(0,0,0,0.06);
          line-height: 1.7;
        }

        h1 {
          font-size: 1.8rem;
          margin: 0 0 8px;
          color: #b91c1c; /* Red tone to signal importance/legal */
          font-weight: 800;
        }

        .lastUpdated {
          font-size: 0.9rem;
          color: #94a3b8;
          margin-bottom: 30px;
        }

        h2 {
          margin-top: 32px;
          margin-bottom: 12px;
          font-size: 1.25rem;
          color: #0f172a;
          font-weight: 700;
          border-bottom: 1px solid #f1f5f9;
          padding-bottom: 8px;
        }

        p {
          margin-bottom: 16px;
          color: #475569;
        }

        ul {
          margin-bottom: 16px;
          padding-left: 24px;
          color: #475569;
        }

        li {
          margin-bottom: 8px;
        }

        .textLink {
          color: #2563eb;
          text-decoration: underline;
        }
        .textLink:hover {
          color: #1d4ed8;
        }

        .copyrightBox {
          margin-top: 32px;
          padding-top: 16px;
          border-top: 1px solid #e2e8f0;
          text-align: center;
        }
        .copyrightBox p {
          font-size: 0.85rem;
          color: #64748b;
          font-weight: 700;
        }

        @media (max-width: 600px) {
          .legalCard {
            padding: 24px;
          }
        }
      `}</style>
    </div>
  );
}
